---
name: pre-commit-check
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit
      - name: pre-commit run all
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: -a
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ failure() }}
        with:
          commit_message: Apply automatic changes
          commit_options: "--no-verify"
          # Optional commit user and author settings
          commit_user_name: Linter Bot
          commit_user_email: noreply@rhythmictech.com
          commit_author: Linter Bot <actions@github.com>
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_PERL: false
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_COFFEE: false
          VALIDATE_GO: false
          VALIDATE_POWERSHELL: false
          VALIDATE_TERRAFORM: false
          VALIDATE_CSS: false
